---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Cleanup harvester directory structure (deletes previous runs data)
      file:
        state: absent
        path: '../assets/'

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Recreate assets directory
      file:
        state: directory
        path: '../assets/'

