---
- hosts: all
  pre_tasks:
    - name: Is Tomcat the webapp server?
      shell: ps -o pid,user,cmd -C java | grep 'org.apache.catalina.startup.Bootstrap'
      register: ps_tomcat
      ignore_errors: True
      when: ansible_system == 'Linux'
      tags:
        - debug

    - name: Initialize tomcat facts
      set_fact:
        webapp_server_product: 'tomcat'
        tomcat_proc_nums: "{{ ps_tomcat.stdout_lines | length }}"
        catalina_base: "{{ item | regex_replace('.*\ -Dcatalina\\.base=(.*?)(\\s+\\-.*|\\s?(org\\.apache\\.catalina\\.startup\\.Bootstrap\ start)?$)', '\\1') }}"
        catalina_home: "{{ item | regex_replace('.*\ -Dcatalina\\.home=(.*?)(\\s+\\-.*|\\s?(org\\.apache\\.catalina\\.startup\\.Bootstrap\ start)?$)', '\\1') }}"
        catalina_tmp: "{{ item | regex_replace('.*\ -Djava\\.io\\.tmpdir=(.*?)(\\s+\\-.*|\\s?(org\\.apache\\.catalina\\.startup\\.Bootstrap\ start)?$)' ,'\\1') }}"
        gc_log_pattern: "{{ item | regex_replace('.*\ -Xloggc:(.*?)(\\s+\\-.*|\\s?(org\\.apache\\.catalina\\.startup\\.Bootstrap\ start)?$)' ,'\\1') }}"
        tomcat_pid: "{{ item | regex_replace('^\\s*([0-9]+) *(.*?) .*$', '\\1') }}"
        tomcat_user: "{{ item | regex_replace('^\\s*([0-9]+) *(.*?) .*$', '\\2') }}"
      when: ps_tomcat.rc == 0
      with_items:
        - "{{ ps_tomcat.stdout_lines }}"
      tags:
        - debug

    - name: debug
      debug:
        var: catalina_base
      tags:
        - debug

  roles:
    - role: tomcat
      when: webapp_server_product is defined and webapp_server_product == 'tomcat' and tomcat_proc_nums > 0
    - role: alfresco
      when: webapp_server_port is defined

