---
- hosts: all
  environment:
    PATH: "{{ lookup('env','PATH') }}:{{ hc_tmp }}/bin"
  pre_tasks:
    - name: Is Tomcat the webapp server?
      shell: ps -o pid,user,cmd -C java | grep 'org.apache.catalina.startup.Bootstrap'
      register: ps_tomcat
      ignore_errors: True
      when: ansible_system == 'Linux'

    - name: Initialize tomcat facts
      set_fact:
        webapp_server_product: 'tomcat'
      when: ps_tomcat is defined and ps_tomcat.rc == 0

  roles:
    - role: tomcat
      when: webapp_server_product is defined and webapp_server_product == 'tomcat' and ps_tomcat is defined and ps_tomcat.stdout_lines | length > 0

- hosts: repo_tiers
  roles:
    - role: alfresco

- hosts: share_tiers
  roles:
    - role: share

- hosts: index_tiers
  roles:
    - role: solr

