---
- name: Clean dd temp perf files (Index)
  file:
    state: absent
    path: "{{ solr_data_dirs.stdout_lines | join('/') }}/.hc_tmp_dd_perf_file.raw"
  become: true
  become_user: "{{ solr_user }}"

