db_platforms:
  postgresql: postgres
  oracle: oracle
  mariadb: mysql
  mysql: mysql
  sqlserver: microsoft

#default set in deroles/default change it here if necessary
#jarver: 0.0.1-SNAPSHOT

jarloc:
  - "../../../../alfresco-db-queries/target/alfresco-db-{{ jarver }}.jar"
  - "../../../../alfresco-db-queries/target/alfresco-db.jar"
  - "alfresco-db-{{ jarver }}.jar"
  - "alfresco-db.jar"
