---
- name: "Archive {{ webapp_server_product }} log files"
  archive:
    dest: "{{ item.archive }}"
    path: "{{ item.logfiles }}"
    mode: 0644
    format: zip
  become: "{{ 'true' if checked_privs.failed == false else 'false' }}"
  become_user: "{{ item.user }}"
  with_items:
    - "{{ to_archive }}"
  notify: Clean up Tomcat archives


- name: Fetch archived log files
  fetch:
    src: "{{ item.archive }}"
    dest: ../assets/{{ inventory_hostname }}/logs/
    flat: yes
  with_items:
    - "{{ to_archive }}"

