---
- name: Set process variables
  include_vars: tomcat_args.yml

- name: Get Tomcat working dir
  stat:
    path: /proc/{{ tomcat_pid }}/cwd
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: tomcat_cwd
  become: yes
  become_user: "{{ tomcat_user }}"

- name: Read Tomcat config file
  xml:
    path: "{{ catalina_base }}/conf/server.xml"
    xpath: /Server/Service/Connector[@protocol='HTTP/1.1']
    content: attribute
    attribute: port
  register: tomcat_connector
  become: yes
  become_user: "{{ tomcat_user }}"
  when: hostvars[inventory_hostname]['webapp_server_port'] is undefined

# WARNING loop order matters as positional arguments are used later in play
- name: Check deployed Tomcat webapps
  stat: 
    path: "{{ catalina_base }}/webapps/{{ item | replace('/','#') }}"
    get_attributes: no
    follow: yes
  register: webapp_path
  ignore_errors: True
  loop:
    - "{{ alfresco_context }}"
    - "{{ share_context }}"
    - "{{ solr_context }}"

- name: Export Alfresco Specific variables
  set_fact:
    alfresco_port: "{% if hostvars[inventory_hostname]['webapp_server_port'] is undefined %}{{ tomcat_connector.matches[0]['Connector']['port'] }}{% else %}{{ hostvars[inventory_hostname]['webapp_server_port'] | default('8080') }}{% endif %}"
    alfresco_base: "{{ catalina_base | default('/usr/share/tomcat') }}"
    alfresco_cwd: "{{ tomcat_cwd }}"
    alfresco_user: "{{ tomcat_user }}"
    alfresco_shared_loader: "{% if alfresco_shared_loader is defined %}{{ alfresco_shared_loader }}{% else %}{{ catalina_base | default('/usr/share/tomcat') }}/shared/classes{% endif %}"
    alfresco_java: "{{ java_bin }}"
  when: webapp_path.results[0].stat.exists == True

- name: Export Share Specific variables
  set_fact:
    share_port: "{% if hostvars[inventory_hostname]['webapp_server_port'] is undefined %}{{ tomcat_connector.matches[0]['Connector']['port'] }}{% else %}{{ hostvars[inventory_hostname]['webapp_server_port'] | default('8080') }}{% endif %}"
    share_base: "{{ catalina_base | default('/usr/share/tomcat') }}"
    share_cwd: "{{ tomcat_cwd }}"
    share_user: "{{ tomcat_user }}"
    share_shared_loader: "{% if share_shared_loader is defined %}{{ share_shared_loader }}{% else %}{{ catalina_base | default('/usr/share/tomcat') }}/shared/classes{% endif %}"
    share_java: "{{ java_bin }}"
  when: webapp_path.results[1].stat.exists == True

- name: Export Solr Specific variables
  set_fact:
    solr_port: "{% if hostvars[inventory_hostname]['webapp_server_port'] is undefined %}{{ tomcat_connector.matches[0]['Connector']['port'] }}{% else %}{{ hostvars[inventory_hostname]['webapp_server_port'] | default('8080') }}{% endif %}"
    solr_base: "{{ catalina_base | default('/usr/share/tomcat') }}"
    solr_cwd: "{{ tomcat_cwd }}"
    solr_user: "{{ tomcat_user }}"
    solr_java: "{{ java_bin }}"
  when: webapp_path.results[2].stat.exists == True

- include: catalina_log.yml

- include: gc_log.yml
  when: outer_loop.find('-Xloggc') != -1

