---
- name: find GC log files
  find:
    paths: "{{ gc_log_dir }}"
    patterns: "{{ gc_log_suffix }}*"
    age: "{{ log_history }}"
  become: "{{ 'true' if checked_privs.failed == false else 'false' }}"
  become_user: "{{ tomcat_user }}"
  register: found_gc_logs

- name: Build the archive dict
  set_fact:
    gc_log_dict: [ { user: "{{ tomcat_user }}", logfiles: "{{ found_gc_logs.files | map(attribute='path') | list }}", archive: "{{ hc_tmp }}/{{ webapp_server_product }}-{{ tomcat_pid }}-GClog.zip" } ]
  when: found_gc_logs.matched > 0

- name: Add GC log files to the list of assets to archive
  set_fact:
    to_archive: "{{ to_archive }} + {{ gc_log_dict }}"
  when: found_gc_logs.matched > 0

