---
- name: Load OS specific vars
  include_vars: "{{ item }}"
  with_first_found:
      - "{{ ansible_os_family|lower }}.yml"
      - "{{ ansible_system|lower }}.yml"
      - "{{ ansible_distribution|lower }}.yml"
      - "{{ ansible_distribution|lower }}_{{ ansible_distribution_major_version|lower }}.yml"
  ignore_errors: true

- include: packages.yml
- include: config.yml
  loop: "{{ ps_tomcat.stdout_lines }}"
  loop_control:
    loop_var: outer_loop
    index_var: outer_loop_key
  when: ps_tomcat is defined

