---
- name: Install required packages
  package:
    name: "{{ item }}"
    update_cache: yes
  become: yes
  with_items:
    - "{{ packages }}"
  when: ( inventory_hostname in groups['index_tiers'] and solr_home is undefined ) or webapp_server_port is undefined

