---
- name: Install required packages
  package:
    name: "{{ item }}"
    update_cache: yes
  become: yes
  with_items:
    - "{{ packages }}"
  when: solr_home is undefined or webapp_server_port is undefined

