---
- name: Create temp dir
  file:
    state: directory
    path: "{{ hc_tmp }}"

- name: Send Alfresco DB queries tool
  copy:
    src: "{{lookup('first_found', jarloc)}}"
    dest: "{{ hc_tmp }}"

- name: Send config and scripts files
  template:
    src: "{{ item.file }}"
    dest: "{{ hc_tmp }}"
    mode: "{{ item.mode }}"
  with_items:
    - { file: application.properties, mode: '644' }
    - { file: alfresco-db-queries.sh, mode: '755' }

- name: Run the DB queries tool
  command: ./alfresco-db-queries.sh chdir={{ hc_tmp }}
  async: 900
  become: "{{ 'yes' if checked_privs.failed == false else 'no' }}"
  become_user: "{{ alfresco_user }}"
  register: alfdbq_run
  notify: Destroy DB queries tool process

- name: Wait for Alfresco-db-queries to be available on port {{ alfresco_db_queries_port }}
  wait_for:
    delay: 5
    sleep: 3
    connect_timeout: 3
    port: "{{ alfresco_db_queries_port }}"

- name: Generate DB queries report
  uri:
    url: http://localhost:{{ alfresco_db_queries_port }}/report
    timeout: "{{ db_queries_report_timeout }}"

- name: Fetch DB queries report
  fetch:
    src: "{{ hc_tmp }}/acs-db-report.csv"
    dest: ../assets/
    flat: yes

