---
- name: Get Alfresco CSRF token
  uri:
    url: http://localhost:{{ alfresco_port }}/{{ alfresco_context }}/s/enterprise/admin/admin-clustering-test
    force_basic_auth: yes
    url_username: "{{ alfresco_admin_user }}"
    url_password: "{{ alfresco_admin_password }}"
  register: csrf_req
  failed_when: csrf_req.status is undefined

- name: Validate Cluster communication
  uri:
    url: http://localhost:{{ alfresco_port }}/{{ alfresco_context }}/s/enterprise/admin/admin-clustering-test
    method: POST
    force_basic_auth: yes
    url_username: "{{ alfresco_admin_user }}"
    url_password: "{{ alfresco_admin_password }}"
    headers: 
      alf-csrftoken: "{{ csrf_req.cookies['alf-csrftoken'] | default('noTokenFound') | urldecode }}"
      Referer: http://localhost:{{ alfresco_port }}/{{ alfresco_context }}/s/enterprise/admin/admin-clustering-test
      Cookie: "{{ csrf_req.set_cookie | default('Dummy=nothingToSet') }}"
  register: cluster_check
  when: csrf_req.status == 200

- name: Save cluster validation results
  template:
    src: cluster-validate.j2
    dest: "{{ hc_tmp }}/cluster-validate.md"

- name: Fetch Cluster Validate results
  fetch:
    src: "{{ hc_tmp }}/cluster-validate.md"
    dest: ../assets/{{ inventory_hostname }}/
    flat: yes

