---
- name: get server info
  uri:
    url: http://localhost:{{ alfresco_port }}/{{ alfresco_context }}/s/api/server
    return_content: yes
  register: srv_info

- name: Read secrets from secured location
  include_vars: secrets.yml

- name: Find Alfresco log files
  find:
    paths: "{{ hostvars[inventory_hostname]['alfresco_log_pattern'] | default(alfresco_cwd.stat.lnk_target + '/placeholder' ) | dirname }}"
    patterns: "{{ hostvars[inventory_hostname]['alfresco_log_pattern'] | default('alfresco.log') | basename }}*"
    age: "{{ log_history }}"
  register: found_alfresco_logs

- name: Archive Alfresco log files
  archive:
    path: "{{ found_alfresco_logs.files | map(attribute='path') | list }}"
    dest: "{{ hc_tmp }}/alfresco-log.tar.gz"
    mode: 0644
  become: yes
  become_user: "{{ alfresco_user }}"
  notify: Clean up Alfresco archives

- name: Archive extension directory
  archive:
    path: "{{ alfresco_shared_loader }}/alfresco/extension"
    dest: "{{ hc_tmp }}/alfresco-extension.tar.gz"
    mode: 0644
  become: yes
  become_user: "{{ alfresco_user }}"
  notify: Clean up Alfresco archives

- name: Fetch archived extension root
  fetch:
    src: "{{ hc_tmp }}/alfresco-extension.tar.gz"
    dest: ../assets/{{ inventory_hostname }}/conf/
    flat: yes

- name: Fetch archived log files
  fetch:
    src: "{{ hc_tmp }}/alfresco-log.tar.gz"
    dest: ../assets/{{ inventory_hostname }}/logs/
    flat: yes

- name: Generate Alfresco JMX dump
  get_url: 
    url: http://localhost:{{ alfresco_port }}/{{ alfresco_context }}/s/api/admin/jmxdump
    dest: "{{ hc_tmp }}/jmxdump-{{ inventory_hostname }}.zip"
    force_basic_auth: yes
    url_username: "{{ alfresco_admin_user }}"
    url_password: "{{ alfresco_admin_password }}"
  notify: Clean up Alfresco archives

- name: Fetch jmxdump
  fetch:
    src: "{{ hc_tmp }}/jmxdump-{{ inventory_hostname }}.zip"
    dest: ../assets/{{ inventory_hostname }}/conf/
    flat: yes

