---
- name: Find Search Service process
  shell: ps -o pid,user,cmd -C java | egrep '\s+-D\s*solr\.' | egrep '\s+--module=http'
  register: ps_search_service
  ignore_errors: true

- name: Copy Solr client certificate and key   
  copy:                                                                                        
    src:  "{{ item }}"
    dest: "{{ hc_tmp }}/{{ item | dirname }}/"                                                                                                                                                 
  with_items:                                                                                  
    - "{{ solr_client_cert | default('solrclient_crt') }}"
    - "{{ solr_client_key | default('solrclient_key') }}"

- include: solr6.yml
  loop: "{{ ps_search_service.stdout_lines }}"
  loop_control:
    loop_var: outer_loop
    index_var: outer_loop_key
  when: ps_search_service is defined and ps_search_service.rc == 0

- include: solr4.yml
  when: ps_search_service.failed | default(false)

- name: get Solr server info
  uri:
    url: "{{ solr_scheme }}://localhost:{{ solr_port }}/{{ solr_context }}/admin/info/system?wt=json"
    return_content: yes
    client_cert: "{{ hc_tmp }}/{{ solr_client_cert | default('solrclient_crt') }}"
    client_key: "{{ hc_tmp }}/{{ solr_client_key | default('solrclient_key') }}"
    validate_certs: no
    status_code:
      - 404
      - 200
  register: solr_info

- name: get Solr (1.4) server info
  uri:
    url: "{{ solr_scheme }}://localhost:{{ solr_port }}/{{ solr_context }}/alfresco/admin/system?wt=json"
    return_content: yes
    client_cert: "{{ hc_tmp }}/{{ solr_client_cert | default('solrclient_crt') }}"
    client_key: "{{ hc_tmp }}/{{ solr_client_key | default('solrclient_key') }}"
    validate_certs: no
  register: "{{ solr_info if solr_info.status == 404 else summy_solr_info_register }}"
  when: solr_info.status == 404

- name: Generate Solr SUMMARY report
  get_url:
    url: "{{ solr_scheme }}://localhost:{{ solr_port }}/{{ solr_context }}/admin/cores?action=SUMMARY&wt=xml"
    dest: "{{ hc_tmp }}/solr-SUMMARY-{{ inventory_hostname }}.xml"
    client_cert: "{{ hc_tmp }}/{{ solr_client_cert | default('solrclient_crt') }}"
    client_key: "{{ hc_tmp }}/{{ solr_client_key | default('solrclient_key') }}"
    timeout: "{{ solr_summary_report_timeout }}"
    validate_certs: no

- name: Fetch Solr SUMMARY report
  fetch:
    src: "{{ hc_tmp }}/solr-SUMMARY-{{ inventory_hostname }}.xml"
    dest: ../assets/{{ inventory_hostname }}/
    flat: yes

- include: index.yml
  when: checked_privs.failed | default(false) == false or checked_solr6_privs.failed | default(false) == false
