---
- name: Search Service
  ansible.builtin.debug:
    msg: 
    - solr_engine is {{ solr_engine }}

- name: Find Search Service process
  shell: ps -o pid,user,cmd -C java | egrep '\s+-D\s*solr\.' | egrep '\s+--module=http'
  register: ps_search_service
  ignore_errors: true

- name: Copy Solr client certificate and key   
  copy:                                                                                        
    src:  "{{ item }}"
    dest: "{{ hc_tmp }}/{{ item | dirname }}/"                                                                                                                                                 
  with_items:                                                                                  
    - "{{ solr_client_cert | default('solrclient_crt') }}"
    - "{{ solr_client_key | default('solrclient_key') }}"
  when: solr_engine == 'solr6' or solr_engine == 'solr4' 

- include: solr6.yml
  loop: "{{ ps_search_service.stdout_lines }}"
  loop_control:
    loop_var: outer_loop
    index_var: outer_loop_key
  when: solr_engine == 'solr6' 

- include: solr4.yml
  when: solr_engine == 'solr4' 

- include: index.yml
  when: checked_privs.failed | default(false) == false or checked_solr6_privs.failed | default(false) == false
