---
- name: Find Search Service process
  shell: ps -o pid,user,cmd -C java | egrep '\s+-server\s+.*solr\.'
  register: ps_search_service
  ignore_errors: true

- name: Copy Solr client certificate and key   
  copy:                                                                                        
    src:  "{{ item }}"
    dest: "{{ hc_tmp }}/{{ item | dirname }}/"                                                                                                                                                 
  with_items:                                                                                  
    - "{{ solr_client_cert | default('solrclient_crt') }}"
    - "{{ solr_client_key | default('solrclient_key') }}"

- include: solr6.yml
  loop: "{{ ps_search_service.stdout_lines }}"
  loop_control:
    loop_var: outer_loop
    index_var: outer_loop_key
  when: ps_search_service is defined and ps_search_service.rc == 0

- name: get Solr server info
  uri:
    url: "{{ solr_scheme }}://localhost:{{ solr_port }}/{{ solr_context }}/admin/info/system?wt=json"
    return_content: yes
    client_cert: "{{ hc_tmp }}/{{ solr_client_cert | default('solrclient_crt') }}"
    client_key: "{{ hc_tmp }}/{{ solr_client_key | default('solrclient_key') }}"
    validate_certs: no
  register: solr_info

- name: Generate Solr SUMMARY report
  get_url:
    url: "{{ solr_scheme }}://localhost:{{ solr_port }}/{{ solr_context }}/admin/cores?action=SUMMARY&wt=xml"
    dest: "{{ hc_tmp }}/solr-SUMMARY-{{ inventory_hostname }}.xml"
    client_cert: "{{ hc_tmp }}/{{ solr_client_cert | default('solrclient_crt') }}"
    client_key: "{{ hc_tmp }}/{{ solr_client_key | default('solrclient_key') }}"
    timeout: "{{ solr_summary_report_timeout }}"
    validate_certs: no

- name: Fetch Solr SUMMARY report
  fetch:
    src: "{{ hc_tmp }}/solr-SUMMARY-{{ inventory_hostname }}.xml"
    dest: ../assets/{{ inventory_hostname }}/
    flat: yes

