---
- name: Archive Share log files
  archive:
    dest: /tmp/share-log.tar.gz
    path: "{{ share_log_pattern }}"
    mode: 0644
  become: yes
  become_user: "{{ share_user }}"
  notify: Clean up Share archives

- name: Archive web-extension directory
  archive:
    dest: /tmp/share-web-extension.tar.gz
    path: "{{ share_shared_loader }}/alfresco/web-extension"
    mode: 0644
  become: yes
  become_user: "{{ share_user }}"
  notify: Clean up Share archives

- name: Fetch archived extension root
  fetch:
    src: /tmp/share-web-extension.tar.gz
    dest: ../assets/{{ inventory_hostname }}/conf/
    flat: yes

- name: Fetch archived log files
  fetch:
    src: /tmp/share-log.tar.gz
    dest: ../assets/{{ inventory_hostname }}/logs/
    flat: yes

