---
- name: Find Share log files
  find:
    paths: "{{ hostvars[inventory_hostname]['share_log_pattern'] | default(share_cwd.stat.lnk_target + '/placeholder' ) | dirname }}"
    patterns: "{{ hostvars[inventory_hostname]['share_log_pattern'] | default('share.log') | basename }}*"
    age: "{{ log_history }}"
  register: found_share_logs

- name: Archive Share log files
  archive:
    path: "{{ found_share_logs.files | map(attribute='path') | list }}"
    dest: "{{ hc_tmp }}/share-log.tar.gz"
    mode: 0644
  become: yes
  become_user: "{{ share_user }}"
  notify: Clean up Share archives

- name: Archive web-extension directory
  archive:
    path: "{{ share_shared_loader }}/alfresco/web-extension"
    dest: "{{ hc_tmp }}/alfresco-web-extension.tar.gz"
    mode: 0644
  become: yes
  become_user: "{{ share_user }}"
  notify: Clean up Share archives

- name: Fetch archived extension root
  fetch:
    src: "{{ hc_tmp }}/alfresco-web-extension.tar.gz"
    dest: ../assets/{{ inventory_hostname }}/conf/
    flat: yes

- name: Fetch archived log files
  fetch:
    src: "{{ hc_tmp }}/share-log.tar.gz"
    dest: ../assets/{{ inventory_hostname }}/logs/
    flat: yes

