---
- name: Find Share log files
  find:
    paths: "{{ hostvars[inventory_hostname]['share_log_pattern'] | default(share_cwd + '/placeholder' ) | dirname }}"
    patterns: "{{ hostvars[inventory_hostname]['share_log_pattern'] | default('share.log*') | basename }}"
    age: "{{ log_history }}"
  become: "{{ 'true' if checked_privs.failed == false else 'false' }}"
  become_user: "{{ share_user }}"
  register: found_share_logs

- name: Archive Share log files
  archive:
    path: "{{ found_share_logs.files | map(attribute='path') | list }}"
    dest: "{{ hc_tmp }}/share-log.zip"
    mode: 0644
    format: zip
  become: "{{ 'true' if checked_privs.failed == false else 'false' }}"
  become_user: "{{ share_user }}"
  when: found_share_logs.matched > 0
  notify: Clean up Share archives

- name: Archive web-extension directory
  archive:
    path: "{{ share_shared_loader }}/alfresco/web-extension"
    dest: "{{ hc_tmp }}/alfresco-web-extension.zip"
    mode: 0644
    format: zip
  become: "{{ 'true' if checked_privs.failed == false else 'false' }}"
  become_user: "{{ share_user }}"
  register: webext_archive
  ignore_errors: True
  notify: Clean up Share archives

- name: Fetch archived extension root
  fetch:
    src: "{{ hc_tmp }}/alfresco-web-extension.zip"
    dest: ../assets/{{ inventory_hostname }}/conf/
    flat: yes
  when: webext_archive.failed == false

- name: Fetch archived log files
  fetch:
    src: "{{ hc_tmp }}/share-log.zip"
    dest: ../assets/{{ inventory_hostname }}/logs/
    flat: yes
  when: found_share_logs.matched > 0

