---
- name: Archive Share log files
  archive:
    dest: "{{ hc_tmp }}/share-log.tar.gz"
    path: "{{ share_cwd.stat.lnk_target }}/share.log*"
    mode: 0644
  become: yes
  become_user: "{{ share_user }}"

- name: Archive extension directory
  archive:
    dest: "{{ hc_tmp }}/alfresco-web-extension.tar.gz"
    path: "{{ share_base }}/shared/classes/alfresco/web-extension"
    mode: 0644
  become: yes
  become_user: "{{ share_user }}"

- name: Fetch archived extension root
  fetch:
    src: "{{ hc_tmp }}/alfresco-web-extension.tar.gz"
    dest: ../assets/{{ inventory_hostname }}/conf/
    flat: yes

- name: Fetch archived log files
  fetch:
    src: "{{ hc_tmp }}/share-log.tar.gz"
    dest: ../assets/{{ inventory_hostname }}/logs/
    flat: yes

