---
- name: Get generic values for this system
  connection: local
  template:
    dest: ../assets/{{ inventory_hostname }}/
    src: system.csv
    newline_sequence: \r\n

- name: Initialize temp directory
  file:
    state: directory
    path: "{{hc_tmp }}"
    mode: 0777
 
