---
- name: Copy sudosu authentication wrapper
  copy:
    src: sudosu-wrapper.sh
    dest: "{{ hc_tmp }}/bin/"
    mode: 0755
  when: ansible_become_exe is defined and ansible_become_exe == hc_tmp + '/bin/sudosu-wrapper.sh'

- name: Check root Privileges
  command: /bin/true
  become: true
  register: checked_root_privs
  ignore_errors: yes

- name: Re-Collect hardware facts as root
  setup:
    gather_subset: hardware
    filter: ansible_mounts
  become: true
  when : checked_root_privs.failed == false and ansible_mounts | length != ansible_mounts | map(attribute='size_total') | list | length

- name: Get generic values for this system
  connection: local
  template:
    dest: ../assets/{{ inventory_hostname }}/
    src: system.csv
    newline_sequence: \r\n

- name : Check network connectivity between hosts
  command: ping {{ item }} -c 12
  register: ping_result
  with_items:
    - "{{ groups['all'] | map('extract', hostvars, 'ansible_default_ipv4') | map(attribute='address') | list }}"
  ignore_errors: yes

- name: Reports network results
  connection: local
  template:
    dest: ../assets/{{ inventory_hostname }}/
    src: ping.txt

- name: Initialize Healtchcheck temp directory
  file:
    state: directory
    path: "{{ hc_tmp }}"
    mode: 0777

