---
 - name: Clean up Alfresco archives
   file:
     state: absent
     path: /tmp/{{ item }}
   with_items:
     - alfresco-log.tar.gz
     - alfresco-extension.tar.gz
     - jmxdump-{{ inventory_hostname }}.zip

