---
- name: Clean up Alfresco archives
  file:
    state: absent
    path: /tmp/{{ item }}
  with_items:
    - alfresco-log.zip
    - alfresco-extension.zip
    - jmxdump-{{ inventory_hostname }}.zip

- name: Clean dd temp perf files (Repository)
  file:
    state: absent
    path: "{{ contentstore_directory | default(contentstore_dir) }}/.hc_tmp_dd_perf_file_{{ inventory_hostname }}.raw"
  become: yes
  become_user: "{{ alfresco_user }}"

